name: lumilu
description: "Move together. Feel better every day."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  equatable: ^2.1.0
  go_router: ^17.2.3
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3

  lumilu_motion:
    path: ../lumilu_motion

  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0

flutter:
  config:
    enable-lldb-debugging: false
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/nav_bar/
    - assets/icons/lumi_tab/
    - assets/images/
    - assets/images/lumi_tab/
    - assets/images/lumi_tab/body/
    - assets/images/lumi_tab/head/
    - assets/images/lumi_tab/clothing/
    - assets/translations/
