name: lumilu
description: "Move together. Feel better every day."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  equatable: ^2.1.0
  go_router: ^17.2.3
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3

  lumilu_motion:
    git:
      url: https://github.com/aleksandrsovtan/lumilu_motion.git
      ref: aa153db197e60dd0beea7049eb25502a05dff34d

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
